name: ➕ Icon request
description: Suggest an icon for this theme!
title: "Icon request: "
labels: enhancement

body:
- type: markdown
  attributes:
    value: "# New icon submission form"
- type: markdown
  attributes:
    value: "Please provide info for the icon(s) you're requesting."
- type: input
  id: icon
  attributes:
   label: Name of app, mime type or folder
   placeholder: AbiWord
  validations:
   required: true
- type: input
  id: link
  attributes:
   label: Link to official icon
   placeholder: Paste a link to the official icon on the project site, WikiMedia, etc. (ideally in `.svg` format)
  validations:
   required: true
- type: input
  id: iconname
  attributes:
   label: Name of icon as referenced in the .desktop file (Flatpak and AppImage apps' icon names often differ from regular ones for the same app).
   placeholder: com.abisource.AbiWord
- type: textarea
  id: screenshot
  attributes:
   label: Optional image of the icon
   placeholder: Drag-and-drop an image or upload from the Markdown toolbar.
- type: textarea
  id: additional
  attributes:
   label: Additional context
   placeholder: Add more information if needed.
